import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../../core/theme/app_spacing.dart';
import '../msme_theme.dart';

class MsmePortalHelpPage extends ConsumerWidget { const MsmePortalHelpPage({super.key}); @override Widget build(BuildContext context, WidgetRef ref) { return Scaffold(backgroundColor: MsmeTheme.bgDark, body: SingleChildScrollView(padding: const EdgeInsets.all(AppSpacing.lg), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Help Center & Support', style: MsmeTheme.headingLarge()), Text('Frequently asked questions, LGU tourism office support, and user guides.', style: MsmeTheme.body(color: MsmeTheme.textMuted)), const SizedBox(height: AppSpacing.lg), Container(padding: const EdgeInsets.all(AppSpacing.lg), decoration: MsmeTheme.cardDecoration(bg: MsmeTheme.primaryOrange.withValues(alpha: 0.1)), child: Row(children: [const Icon(Icons.support_agent_rounded, color: MsmeTheme.primaryOrange, size: 36), const SizedBox(width: 16), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Tubigon Municipal Tourism Office', style: GoogleFonts.plusJakartaSans(color: MsmeTheme.textWhite, fontWeight: FontWeight.bold, fontSize: 16)), Text('Hotline: +63 38 508 8000 • Email: tourism@tubigon.gov.ph', style: GoogleFonts.inter(color: MsmeTheme.textMuted, fontSize: 13))]))])), const SizedBox(height: AppSpacing.lg), Text('Frequently Asked Questions', style: MsmeTheme.headingSmall()), const SizedBox(height: AppSpacing.md), const _FaqTile(question: 'How do I verify my MSME business license?', answer: 'Submit your Mayor\'s Permit or DTI Registration to the Tubigon LGU Tourism Office or upload your document scan via Business Profile settings.'), const _FaqTile(question: 'What happens when a guest requests a booking?', answer: 'You will receive an instant notification. Go to the Reservations page to accept or reject the booking.'), const _FaqTile(question: 'How do I issue discount coupons?', answer: 'Navigate to Promotions & Discounts and click "Create Promotion" to set coupon codes and discount percentages.')]))); } }

class _FaqTile extends StatelessWidget { final String question; final String answer; const _FaqTile({required this.question, required this.answer}); @override Widget build(BuildContext context) { return Container(margin: const EdgeInsets.only(bottom: 12), decoration: MsmeTheme.cardDecoration(), child: ExpansionTile(title: Text(question, style: GoogleFonts.inter(color: MsmeTheme.textWhite, fontWeight: FontWeight.w600, fontSize: 14)), iconColor: MsmeTheme.primaryOrange, collapsedIconColor: MsmeTheme.textMuted, children: [Padding(padding: const EdgeInsets.fromLTRB(16, 0, 16, 16), child: Text(answer, style: GoogleFonts.inter(color: MsmeTheme.textMuted, fontSize: 13, height: 1.4)))])); } }

