import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../../../core/theme/app_spacing.dart';
import '../msme_theme.dart';

class MsmePortalPromotionsPage extends ConsumerStatefulWidget { const MsmePortalPromotionsPage({super.key}); @override ConsumerState<MsmePortalPromotionsPage> createState() => _MsmePortalPromotionsPageState(); }
class _MsmePortalPromotionsPageState extends ConsumerState<MsmePortalPromotionsPage> { final List<Map<String, dynamic>> _promotions = [{'id': 'PROMO-01','code': 'TUBIGONFEST15','title': 'Fiesta Season Special Discount','discount': '15% OFF','valid': 'Aug 1 - Aug 31, 2026','status': 'Active',},{'id': 'PROMO-02','code': 'LOOMWEAVE20','title': 'Raffia Crafts Early Bird Coupon','discount': '20% OFF','valid': 'Aug 15 - Sep 15, 2026','status': 'Scheduled',},]; @override Widget build(BuildContext context) { return Scaffold(backgroundColor: MsmeTheme.bgDark, body: Padding(padding: const EdgeInsets.all(AppSpacing.lg), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Promotions & Discounts', style: MsmeTheme.headingLarge()), Text('Create discount coupons, seasonal offers, and promotional deals.', style: MsmeTheme.body(color: MsmeTheme.textMuted))]), ElevatedButton.icon(style: ElevatedButton.styleFrom(backgroundColor: MsmeTheme.primaryOrange, foregroundColor: Colors.white, padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 12), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10))), onPressed: _showCreatePromoDialog, icon: const Icon(Icons.local_offer_rounded, size: 18), label: const Text('Create Promotion', style: TextStyle(fontWeight: FontWeight.bold)))]), const SizedBox(height: AppSpacing.lg), Expanded(child: ListView.builder(itemCount: _promotions.length, itemBuilder: (context, index) { final p = _promotions[index]; return Container(margin: const EdgeInsets.only(bottom: AppSpacing.md), padding: const EdgeInsets.all(AppSpacing.lg), decoration: MsmeTheme.cardDecoration(), child: Row(children: [Container(width: 48, height: 48, decoration: BoxDecoration(color: MsmeTheme.orangeDim, borderRadius: BorderRadius.circular(12)), child: const Icon(Icons.discount_rounded, color: MsmeTheme.primaryOrange, size: 24)), const SizedBox(width: 16), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Text(p['title']!, style: GoogleFonts.inter(color: MsmeTheme.textWhite, fontWeight: FontWeight.bold, fontSize: 14)), const SizedBox(width: 10), MsmeBadge(label: p['code']!, type: MsmeBadgeType.amber)]), const SizedBox(height: 4), Text('Valid: ${p['valid']}', style: GoogleFonts.inter(color: MsmeTheme.textMuted, fontSize: 12))])), Text(p['discount']!, style: GoogleFonts.plusJakartaSans(color: MsmeTheme.greenLight, fontWeight: FontWeight.w900, fontSize: 18)), const SizedBox(width: 16), MsmeBadge(label: p['status']!, type: p['status'] == 'Active' ? MsmeBadgeType.green : MsmeBadgeType.blue)])); }))],),),); }
	void _showCreatePromoDialog() { final titleCtrl = TextEditingController(); final codeCtrl = TextEditingController(); final discountCtrl = TextEditingController(); showDialog(context: context, builder: (ctx) => AlertDialog(backgroundColor: MsmeTheme.cardDark, title: Text('Create New Promotion', style: GoogleFonts.plusJakartaSans(color: Colors.white, fontWeight: FontWeight.bold)), content: Column(mainAxisSize: MainAxisSize.min, children: [TextField(controller: titleCtrl, style: const TextStyle(color: MsmeTheme.textWhite), decoration: const InputDecoration(labelText: 'Promotion Name', labelStyle: TextStyle(color: MsmeTheme.textMuted))), const SizedBox(height: 10), TextField(controller: codeCtrl, style: const TextStyle(color: MsmeTheme.textWhite), decoration: const InputDecoration(labelText: 'Coupon Code (e.g. SUMMER10)', labelStyle: TextStyle(color: MsmeTheme.textMuted))), const SizedBox(height: 10), TextField(controller: discountCtrl, style: const TextStyle(color: MsmeTheme.textWhite), decoration: const InputDecoration(labelText: 'Discount Rate (e.g. 15% OFF)', labelStyle: TextStyle(color: MsmeTheme.textMuted)))]), actions: [TextButton(onPressed: () => Navigator.pop(ctx), child: Text('Cancel', style: GoogleFonts.inter(color: MsmeTheme.textMuted))), ElevatedButton(style: ElevatedButton.styleFrom(backgroundColor: MsmeTheme.primaryOrange), onPressed: () { if (titleCtrl.text.isNotEmpty) { setState(() { _promotions.add({'id': 'PROMO-${_promotions.length + 1}','code': codeCtrl.text.toUpperCase(),'title': titleCtrl.text.trim(),'discount': discountCtrl.text.trim(),'valid': 'Aug 2026','status': 'Active',}); }); } Navigator.pop(ctx); }, child: const Text('Create Promo', style: TextStyle(color: Colors.white)))])); }
}

