import 'en.dart';

/// Cebuano (Bisaya) translation strings for Tour Tubigon. English values are
/// inherited only for legacy keys that have not yet received an app-owned
/// translation, so every supported locale always has a safe string.
final Map<String, String> cebStrings = {
  ...enStrings,
  // ── App ────────────────────────────────────────────────────────────────────
  'app_name': 'Tour Tubigon',
  'app_tagline': 'Tuklasin ang Kasingkasing sa Bohol',

  // ── Navigation ─────────────────────────────────────────────────────────────
  'nav_home': 'Panimalay',
  'nav_explore': 'Tuklas',
  'nav_map': 'Mapa',
  'nav_bookings': 'Reserbasyon',
  'nav_profile': 'Profilo',

  // ── Onboarding ─────────────────────────────────────────────────────────────
  'onboarding_1_title': 'Tuklasin ang Tubigon',
  'onboarding_1_desc':
      'Bisita ang mga dalampasigan, kalikasan, ug makasaysayang lugar sa Tubigon, Bohol.',
  'onboarding_2_title': 'Plano ang Imong Byahe',
  'onboarding_2_desc':
      'Storyaon ang imong itinerary ug mag-book og aktibidad ug ferry sa dali.',
  'onboarding_3_title': 'Responsableng Pagbiyahe',
  'onboarding_3_desc':
      'Sunod sa eco-friendly nga mga tips ug tabang ampingi ang kagandahan sa Tubigon.',
  'onboarding_4_title': 'Magkonekta',
  'onboarding_4_desc':
      'Gamit offline, dawata ang real-time updates, ug mag-ugnay sa lokal nga negosyo.',
  'get_started': 'Sugdi',
  'skip': 'Priso',
  'next': 'Sunod',

  // ── Auth ───────────────────────────────────────────────────────────────────
  'login': 'Login',
  'register': 'Mag-rehistro',
  'logout': 'Mag-logout',
  'email': 'Email',
  'password': 'Password',
  'confirm_password': 'Kumpirma ang Password',
  'forgot_password': 'Nalimtan ang Password?',
  'remember_me': 'Hinumdomi ako',
  'no_account': 'Wala pay account?',
  'have_account': 'Aduna nay account?',
  'sign_up': 'Mag-Sign Up',
  'sign_in': 'Mag-Sign In',
  'full_name': 'Tibuok Ngalan',
  'phone_number': 'Numero sa Telepono',
  'i_am_a': 'Ako usa ka',
  'tourist': 'Turista',
  'msme_owner': 'Tag-iya sa Negosyo',
  'terms_agree': 'Miuyon ko sa Terms of Service ug Privacy Policy',

  // ── Dashboard ──────────────────────────────────────────────────────────────
  'good_morning': 'Maayong buntag',
  'good_afternoon': 'Maayong hapon',
  'good_evening': 'Maayong gabii',
  'weekday_1': 'Lunes',
  'weekday_2': 'Martes',
  'weekday_3': 'Miyerkules',
  'weekday_4': 'Huwebes',
  'weekday_5': 'Biyernes',
  'weekday_6': 'Sabado',
  'weekday_7': 'Domingo',
  'month_1': 'Enero',
  'month_2': 'Pebrero',
  'month_3': 'Marso',
  'month_4': 'Abril',
  'month_5': 'Mayo',
  'month_6': 'Hunyo',
  'month_7': 'Hulyo',
  'month_8': 'Agosto',
  'month_9': 'Septiyembre',
  'month_10': 'Oktubre',
  'month_11': 'Nobyembre',
  'month_12': 'Disyembre',
  'welcome_to': 'Maligayon sa',
  'featured_spots': 'Piling mga Lugar',
  'popular_destinations': 'Sikat nga Destinasyon',
  'upcoming_reservations': 'Sunod nga Reserbasyon',
  'quick_actions': 'Dali nga Aksyon',
  'recently_viewed': 'Bag-o lang Gitan-aw',
  'nearby_attractions': 'Duol nga Atraksyon',
  'see_all': 'Tan-awa Tanan',

  // ── Tourist Spots ──────────────────────────────────────────────────────────
  'tourist_spots': 'Mga Turista nga Lugar',
  'search_spots': 'Pangita og lugar...',
  'filter': 'Salain',
  'sort': 'Ayoha',
  'categories': 'Kategorya',
  'all': 'Tanan',
  'beach': 'Baybay',
  'nature': 'Kinaiyahan',
  'historical': 'Kasaysayan',
  'cultural': 'Kultura',
  'adventure': 'Pakigsabot',
  'food': 'Pagkaon',
  'eco': 'Eko',
  'accommodation': 'Pulonanan',
  'entrance_fee': 'Bayad sa Pagsulod',
  'free': 'Libre',
  'opening_hours': 'Orasa sa Pagbukas',
  'reviews': 'Mga Review',
  'write_review': 'Magsulat og Review',
  'navigate': 'Direksyon',
  'share': 'I-share',
  'add_to_favorites': 'Idugang sa Paborito',
  'remove_from_favorites': 'Kuhaa sa Paborito',

  // ── Common ─────────────────────────────────────────────────────────────────
  'loading': 'Nag-load...',
  'loading_map': 'Nag-load sa mapa…',
  'retry': 'Sulayi Pag-usab',
  'save': 'I-save',
  'cancel': 'Kanselaha',
  'delete': 'Kuhaa',
  'edit': 'I-edit',
  'done': 'Tapos',
  'back': 'Balik',
  'close': 'Sirado',
  'confirm': 'Kumpirma',
  'yes': 'Oo',
  'no': 'Dili',
  'ok': 'OK',
  'error': 'Sayop',
  'success': 'Nalampasan',
  'offline': 'Offline',
  'no_connection': 'Walay koneksyon sa internet',
  'km_away': 'km ang gilay-on',
  'updated': 'Na-update',
  'reservations': 'Mga Reserbasyon',
  'book_now': 'Magpareserba',
  'ferry_schedules': 'Mga Iskedyul sa Barko',
  'departure': 'Pagbiya',
  'arrival': 'Pag-abot',
  'fare': 'Plete',
  'operator': 'Operator',
  'eco_tips': 'Mga Eco Tip',
  'emergency_contacts': 'Mga Kontak sa Emerhensiya',
  'call': 'Tawag',
  'carbon_estimator': 'Banabana sa Carbon Footprint',
  'report_issue': 'I-report ang Problema',
  'my_waste_reports': 'Akong mga Waste Report',
  'photo_evidence': 'Litrato nga Ebidensya',
  'barangay_optional': 'Barangay (opsyonal)',
  'estimate_trip_footprint': 'Banabanaa ang Carbon sa Biyahe',
  'travel_mode': 'Paagi sa pagbiyahe',
  'distance_km': 'Distansya usa ka padulngan (km)',
  'number_of_travelers': 'Gidaghanon sa biyahero',
  'one_way': 'Usa ka padulngan',
  'round_trip': 'Balikan',
  'estimated_footprint': 'Gibanabanang footprint',
  'showing_saved_information':
      'Nagpakita sa gitipig nga impormasyon. Posibleng karaan ang ubang detalye.',
  'carbon_intro':
      'Itandi ang gibanabanang carbon sa biyahe gamit ang kasagarang transport factors.',
  'distance_help': 'Gamita ang mapa o odometer; kutob sa 5,000 km.',
  'travelers_help': 'Ang banabana naggamit og passenger-kilometers.',
  'method_note': 'Pamaagi sa pagkalkula',
  'carbon_method':
      'Kini usa lamang ka banabana gamit ang kasagarang factors, dili eksaktong sukod sa sakyanan o barko. Ang pasahero, gasolina, trapiko, ug kahimtang makaapekto sa tinuod nga emissions. Zero ang direktang emissions sa paglakaw ug bisikleta; wala giapil ang lifecycle impacts. Proxy lamang ang tricycle kay walay napamatud-ang Tubigon fleet factor.',
  'issue_category': 'Kategorya sa Problema',
  'location_landmark': 'Lugar / Timailhan',
  'use_current_gps': 'Gamita ang GPS',
  'adjust_on_map': 'I-adjust sa Mapa',
  'issue_description': 'Deskripsyon sa Problema',
  'submit_waste_report': 'Ipadala ang Waste Report',
  'remove': 'Kuhaa',
  'status_history': 'Kasaysayan sa status',
  'eco_guidelines': 'Mga Giya sa Eco-Tourism',
  'advisory': 'Pahibalo',
  'contact': 'Kontak',
  'hours': 'Oras',
  'availability': 'Pagkaanaa',
  'view_map': 'Tan-awa ang Mapa',
  'navigate_upper': 'Direksyon',
  'offline_maps': 'Offline nga mga Mapa',
  'tubigon_offline_map': 'Offline nga Mapa sa Tubigon',
  'download_offline_map': 'I-download ang Offline nga Mapa',
  'download_offline_data': 'I-download ang Offline nga Datos',
  'open_offline_map': 'Ablihi ang Offline nga Mapa',
  'update_offline_data': 'I-update ang Offline nga Datos',
  'delete_offline_package': 'Papasa ang Offline nga Pakete',
  'downloaded': 'Na-download',
  'last_synced': 'Kataposang gi-sync',
  'places': 'Mga Lugar',
  'storage_used': 'Gigamit nga storage',
  'ready': 'Andam',
  'data_only': 'Datos lamang',
  'not_downloaded': 'Wala pa ma-download',
  'included_offline': 'Apil sa offline',
  'offline_places': 'Gipatik nga mga lugar ug detalye',
  'offline_markers_search':
      'Mga marker, label, kategorya, ug lokal nga pagpangita',
  'offline_gps_distance': 'GPS ug tul-id nga gilay-on',
  'offline_emergency_ferry': 'Mga snapshot sa emerhensiya ug ferry',
  'offline_trip_summaries': 'Gitipig nga itinerary ug summary sa reserbasyon',
  'offline_basemap_resources': 'Permanenteng MapLibre base-map resources',
  'web_basemap_unavailable': 'Dili magamit ang tibuok offline base map sa Web',
  'download_paused': 'Gipahunong ang download',
  'validating_download': 'Gisusi ang na-download nga mapa',
  'downloading_map_resources': 'Gina-download ang mga resource sa mapa',
  'updating_offline_data': 'Gina-update ang offline nga datos',
  'download_progress_retained': 'Gitipigan ang progreso sa imong download.',
  'resume': 'Ipadayon',
  'pause': 'Pahunong',
  'offline_storage': 'Offline nga storage',
  'map_resources': 'Mga resource sa mapa',
  'place_information': 'Impormasyon sa lugar',
  'total_measured': 'Kinatibuk-ang nasukod',
  'offline_storage_note':
      'Ang opsyonal nga image cache gidumala sa platform ug wala maapil niining sukod.',
  'web_data_only_explanation':
      'Datos sa mga lugar lamang ang natipig sa browser. Walay permanenteng offline base map sa Web, busa dili kini ablihan isip kompleto nga offline nga mapa.',
  'download_tubigon_offline_map': 'I-download ang Offline nga Mapa sa Tubigon',
  'download_native_explanation':
      'I-download niini ang datos sa mga lugar, safety ug trip snapshots, ug permanenteng MapLibre resources sa Tubigon.',
  'download_web_explanation':
      'Tipigan niini ang datos sa mga lugar ug suportadong snapshots. Dili suportado ang tibuok offline base map sa Web.',
  'download': 'I-download',
  'delete_offline_title': 'Papason ang na-download nga pakete sa Tubigon?',
  'delete_offline_explanation':
      'Papason niini ang mga resource sa mapa ug publikong offline nga datos. Dili mapapas ang Favorites, Itineraries, ug Reservations sa server.',
  'offline_error_connection_required':
      'Konektar sa internet aron ma-download ang offline nga mapa sa Tubigon.',
  'offline_error_map_resources':
      'Natipig ang datos sa lugar, apan wala ma-download ang mga resource sa mapa.',
  'offline_error_download': 'Dili ma-download ang offline nga mapa.',
  'offline_error_interrupted':
      'Naputol ang download sa mapa. Mahimo nimong sulayan pag-usab.',
  'offline_error_validation':
      'Wala makapasar sa pagsusi ang mga resource. Gitipigan ang imong daang pakete.',
  'offline_error_delete': 'Dili mapapas ang offline nga pakete karon.',
  'offline_error_restore':
      'Dili masusi ang gitipig nga mapa niini nga device. I-download kini pag-usab sa dili pa mogamit og offline mode.',
  'offline_package_unavailable':
      'Walay napamatud-ang Tubigon offline map package niini nga device. I-download ug susiha una kini sa dili pa ablihan ang offline mode.',
  'open_online_map': 'Ablihi ang Online nga Mapa',
  'concerns_support': 'Mga Kabalaka ug Suporta',
  'submit_concern': 'Ipadala ang Kabalaka',
  'no_concerns': 'Walay gipadalang kabalaka.',
  'concern': 'Kabalaka',
  'category': 'Kategorya',
  'subject': 'Hilisgutan',
  'details': 'Mga Detalye',
  'priority': 'Prayoridad',
  'related_to_optional': 'May kalabotan sa (opsyonal)',
  'related_record': 'May kalabotang rekord',
  'no_related_records':
      'Walay makit-an nga rekord nga mahimo nimong ma-access.',
  'attach_image_optional': 'I-attach ang hulagway (opsyonal)',
  'attachment_requirements': 'JPEG, PNG, o WebP hangtod 5 MB',
  'draft_attachment_reattach':
      'I-attach pag-usab kining file sa dili pa ipadala.',
  'save_draft': 'Tipigi ang Draft',
  'draft_saved': 'Natipig ang draft niini nga device.',
  'draft_saved_offline': 'Offline ka, busa gitipig ang kabalaka isip draft.',
  'submit': 'Ipadala',
  'complete_concern_details':
      'Kompletoha ang gikinahanglang detalye sa kabalaka.',
  'related_to': 'May kalabotan sa',
  'attachment': 'Attachment',
  'status': 'Kahimtang',
  'replies': 'Mga Tubag',
  'reply': 'Tubag',
  'send': 'Ipadala',
  'staff_concern_subtitle':
      'Ribyuha ang gi-route nga mga tiket nga dili ibutyag ang internal notes.',
  'new_status': 'Bag-o',
  'assigned': 'Gi-assign',
  'in_progress': 'Giproseso',
  'resolved': 'Nasulbad',
  'no_routed_concerns': 'Walay gi-route nga kabalaka.',
  'internal_staff_note': 'Internal nga nota sa staff',
  'visible_to_tourist': 'Makita sa turista',
  'workflow_status': 'Kahimtang sa workflow',
  'reply_workflow_note': 'Tubag o nota sa workflow',
  'internal_note': 'Internal nga nota',
  'never_shown_tourist': 'Dili gayod ipakita sa turista.',
  'escalate_to_admin': 'Ipataas ngadto sa Admin',
  'save_update': 'Tipigi ang Update',
  'network_action_required':
      'Gikinahanglan ang internet para niini nga aksyon.',
  'check_entered_information': 'Susiha ang imong gisulod nga impormasyon.',
  'not_authorized': 'Wala kay pagtugot sa pag-access niini nga kabalaka.',
  'operation_failed': 'Wala makompleto ang operasyon. Sulayi pag-usab.',
  'guidance_reservation':
      'Ang pangutana sa reserbasyon kasagarang mas paspas pinaagi sa Reservation Messages. Mahimo gihapon ka mopadala dinhi.',
  'guidance_waste':
      'Gamita ang Waste Report para sa insidente sa basura nga adunay lokasyon. Padayon dinhi para sa kinatibuk-ang kabalaka.',
  'guidance_emergency':
      'Para sa dihadiha nga peligro, tawagi ang Emergency Contact. Gamita lang kini para sa pagtul-id sa impormasyon.',
  'guidance_related':
      'Pagpili og may kalabotang rekord kon makatabang kini sa staff sa pagsusi sa kabalaka.',
  'concern_category_general-tourism': 'Kinatibuk-ang Kabalaka sa Turismo',
  'concern_category_tourist-spot': 'Impormasyon sa Pasyalan',
  'concern_category_reservation': 'Reserbasyon / Booking',
  'concern_category_ferry': 'Iskedyul sa Ferry',
  'concern_category_msme': 'Impormasyon sa MSME / Negosyo',
  'concern_category_waste': 'Kabalaka sa Basura / Kalikupan',
  'concern_category_emergency-correction':
      'Pagtul-id sa Impormasyon sa Emerhensiya',
  'concern_category_account-login': 'Account / Login',
  'concern_category_role-application': 'Aplikasyon sa Papel',
  'concern_category_technical': 'Problema sa Sistema / Teknikal',
  'concern_category_feedback': 'Sugyot / Feedback',
  'concern_category_other': 'Uban pa',
  'label_low': 'Ubos',
  'label_normal': 'Normal',
  'label_high': 'Taas',
  'label_submitted': 'Gipadala',
  'label_under_review': 'Gina-review',
  'label_assigned': 'Gi-assign',
  'label_in_progress': 'Giproseso',
  'label_needs_more_information': 'Nagkinahanglan og Dugang Impormasyon',
  'label_resolved': 'Nasulbad',
  'label_closed': 'Gisirhan',
  'label_reopened': 'Giablihan Pag-usab',
  'language': 'Pinulongan',
  'select_language': 'Pilia ang Pinulongan',
  'english': 'Iningles',
  'filipino': 'Filipino',
  'cebuano': 'Cebuano (Bisaya)',
  'map_category_plaza-park': 'Mga Plaza ug Parke',
  'map_category_church-place-of-worship': 'Mga Simbahan ug Dapit sa Pagsimba',
};
