/// Cebuano (Bisaya) translation strings for Tubigon Smart Tourism App.
const Map<String, String> cebStrings = {
  // ── App ────────────────────────────────────────────────────────────────────
  'app_name': 'Tubigon Smart Tourism',
  'app_tagline': 'Tuklasin ang Kasingkasing sa Bohol',

  // ── Navigation ─────────────────────────────────────────────────────────────
  'nav_home': 'Panimalay',
  'nav_explore': 'Tuklas',
  'nav_map': 'Mapa',
  'nav_bookings': 'Reserbasyon',
  'nav_profile': 'Profilo',

  // ── Onboarding ─────────────────────────────────────────────────────────────
  'onboarding_1_title': 'Tuklasin ang Tubigon',
  'onboarding_1_desc': 'Bisita ang mga dalampasigan, kalikasan, ug makasaysayang lugar sa Tubigon, Bohol.',
  'onboarding_2_title': 'Plano ang Imong Byahe',
  'onboarding_2_desc': 'Storyaon ang imong itinerary ug mag-book og aktibidad ug ferry sa dali.',
  'onboarding_3_title': 'Responsableng Pagbiyahe',
  'onboarding_3_desc': 'Sunod sa eco-friendly nga mga tips ug tabang ampingi ang kagandahan sa Tubigon.',
  'onboarding_4_title': 'Magkonekta',
  'onboarding_4_desc': 'Gamit offline, dawata ang real-time updates, ug mag-ugnay sa lokal nga negosyo.',
  'get_started': 'Sugdi',
  'skip': 'Priso',
  'next': 'Sunod',

  // ── Auth ───────────────────────────────────────────────────────────────────
  'login': 'Login',
  'register': 'Mag-rehistro',
  'logout': 'Mag-logout',
  'email': 'Email',
  'password': 'Password',
  'confirm_password': 'Kumpirma ang Password',
  'forgot_password': 'Nalimtan ang Password?',
  'remember_me': 'Hinumdomi ako',
  'no_account': 'Wala pay account?',
  'have_account': 'Aduna nay account?',
  'sign_up': 'Mag-Sign Up',
  'sign_in': 'Mag-Sign In',
  'full_name': 'Tibuok Ngalan',
  'phone_number': 'Numero sa Telepono',
  'i_am_a': 'Ako usa ka',
  'tourist': 'Turista',
  'msme_owner': 'Tag-iya sa Negosyo',
  'terms_agree': 'Miuyon ko sa Terms of Service ug Privacy Policy',

  // ── Dashboard ──────────────────────────────────────────────────────────────
  'good_morning': 'Maayong buntag',
  'good_afternoon': 'Maayong hapon',
  'good_evening': 'Maayong gabii',
  'welcome_to': 'Maligayon sa',
  'featured_spots': 'Piling mga Lugar',
  'popular_destinations': 'Sikat nga Destinasyon',
  'upcoming_reservations': 'Sunod nga Reserbasyon',
  'quick_actions': 'Dali nga Aksyon',
  'recently_viewed': 'Bag-o lang Gitan-aw',
  'nearby_attractions': 'Duol nga Atraksyon',
  'see_all': 'Tan-awa Tanan',

  // ── Tourist Spots ──────────────────────────────────────────────────────────
  'tourist_spots': 'Mga Turista nga Lugar',
  'search_spots': 'Pangita og lugar...',
  'filter': 'Salain',
  'sort': 'Ayoha',
  'categories': 'Kategorya',
  'all': 'Tanan',
  'beach': 'Baybay',
  'nature': 'Kinaiyahan',
  'historical': 'Kasaysayan',
  'cultural': 'Kultura',
  'adventure': 'Pakigsabot',
  'food': 'Pagkaon',
  'eco': 'Eko',
  'accommodation': 'Pulonanan',
  'entrance_fee': 'Bayad sa Pagsulod',
  'free': 'Libre',
  'opening_hours': 'Orasa sa Pagbukas',
  'reviews': 'Mga Review',
  'write_review': 'Magsulat og Review',
  'navigate': 'Direksyon',
  'share': 'I-share',
  'add_to_favorites': 'Idugang sa Paborito',
  'remove_from_favorites': 'Kuhaa sa Paborito',

  // ── Common ─────────────────────────────────────────────────────────────────
  'loading': 'Nag-load...',
  'retry': 'Sulayi Pag-usab',
  'save': 'I-save',
  'cancel': 'Kanselaha',
  'delete': 'Kuhaa',
  'edit': 'I-edit',
  'done': 'Tapos',
  'back': 'Balik',
  'close': 'Sirado',
  'confirm': 'Kumpirma',
  'yes': 'Oo',
  'no': 'Dili',
  'ok': 'OK',
  'error': 'Sayop',
  'success': 'Nalampasan',
  'offline': 'Offline',
  'no_connection': 'Walay koneksyon sa internet',
  'km_away': 'km ang gilay-on',
  'updated': 'Na-update',
};
