/// English translation strings for Tour Tubigon.
const Map<String, String> enStrings = {
  // ── App ────────────────────────────────────────────────────────────────────
  'app_name': 'Tour Tubigon',
  'app_tagline': 'Discover the Heart of Bohol',

  // ── Navigation ─────────────────────────────────────────────────────────────
  'nav_home': 'Home',
  'nav_explore': 'Explore',
  'nav_map': 'Map',
  'nav_bookings': 'Bookings',
  'nav_profile': 'Profile',

  // ── Onboarding ─────────────────────────────────────────────────────────────
  'onboarding_1_title': 'Discover Tubigon',
  'onboarding_1_desc':
      'Explore pristine beaches, lush nature trails, and historical landmarks in the heart of Bohol.',
  'onboarding_2_title': 'Plan Your Journey',
  'onboarding_2_desc':
      'Create personalized itineraries and book activities, accommodations, and ferry schedules with ease.',
  'onboarding_3_title': 'Travel Responsibly',
  'onboarding_3_desc':
      'Follow eco-friendly tips and help keep Tubigon\'s natural beauty alive for future generations.',
  'onboarding_4_title': 'Stay Connected',
  'onboarding_4_desc':
      'Access everything offline, get real-time updates, and connect with local businesses and the LGU.',
  'get_started': 'Get Started',
  'skip': 'Skip',
  'next': 'Next',

  // ── Auth ───────────────────────────────────────────────────────────────────
  'login': 'Log In',
  'register': 'Create Account',
  'logout': 'Log Out',
  'email': 'Email',
  'password': 'Password',
  'confirm_password': 'Confirm Password',
  'forgot_password': 'Forgot Password?',
  'remember_me': 'Remember me',
  'no_account': 'Don\'t have an account?',
  'have_account': 'Already have an account?',
  'sign_up': 'Sign Up',
  'sign_in': 'Sign In',
  'full_name': 'Full Name',
  'phone_number': 'Phone Number',
  'i_am_a': 'I am a',
  'tourist': 'Tourist',
  'msme_owner': 'Business Owner',
  'terms_agree': 'I agree to the Terms of Service and Privacy Policy',

  // ── Dashboard ──────────────────────────────────────────────────────────────
  'good_morning': 'Good morning',
  'good_afternoon': 'Good afternoon',
  'good_evening': 'Good evening',
  'weekday_1': 'Monday',
  'weekday_2': 'Tuesday',
  'weekday_3': 'Wednesday',
  'weekday_4': 'Thursday',
  'weekday_5': 'Friday',
  'weekday_6': 'Saturday',
  'weekday_7': 'Sunday',
  'month_1': 'January',
  'month_2': 'February',
  'month_3': 'March',
  'month_4': 'April',
  'month_5': 'May',
  'month_6': 'June',
  'month_7': 'July',
  'month_8': 'August',
  'month_9': 'September',
  'month_10': 'October',
  'month_11': 'November',
  'month_12': 'December',
  'welcome_to': 'Welcome to',
  'featured_spots': 'Featured Spots',
  'popular_destinations': 'Popular Destinations',
  'upcoming_reservations': 'Upcoming Reservations',
  'quick_actions': 'Quick Actions',
  'recently_viewed': 'Recently Viewed',
  'nearby_attractions': 'Nearby Attractions',
  'see_all': 'See All',

  // ── Tourist Spots ──────────────────────────────────────────────────────────
  'tourist_spots': 'Tourist Spots',
  'search_spots': 'Search spots...',
  'filter': 'Filter',
  'sort': 'Sort',
  'categories': 'Categories',
  'all': 'All',
  'beach': 'Beach',
  'nature': 'Nature',
  'historical': 'Historical',
  'cultural': 'Cultural',
  'adventure': 'Adventure',
  'food': 'Food',
  'eco': 'Eco',
  'accommodation': 'Accommodation',
  'entrance_fee': 'Entrance Fee',
  'free': 'Free',
  'opening_hours': 'Opening Hours',
  'reviews': 'Reviews',
  'write_review': 'Write a Review',
  'navigate': 'Navigate',
  'share': 'Share',
  'add_to_favorites': 'Add to Favorites',
  'remove_from_favorites': 'Remove from Favorites',

  // ── Reservations ───────────────────────────────────────────────────────────
  'reservations': 'Reservations',
  'book_now': 'Book Now',
  'select_date': 'Select Date',
  'select_time': 'Select Time',
  'number_of_guests': 'Number of Guests',
  'confirm_booking': 'Confirm Booking',
  'cancel_reservation': 'Cancel',
  'reschedule': 'Reschedule',
  'pending': 'Pending',
  'confirmed': 'Confirmed',
  'cancelled': 'Cancelled',
  'completed': 'Completed',

  // ── Ferry ──────────────────────────────────────────────────────────────────
  'ferry_schedules': 'Ferry Schedules',
  'tubigon_to_cebu': 'Tubigon → Cebu',
  'cebu_to_tubigon': 'Cebu → Tubigon',
  'departure': 'Departure',
  'arrival': 'Arrival',
  'fare': 'Fare',
  'operator': 'Operator',
  'on_time': 'On Time',
  'delayed': 'Delayed',

  // ── Eco ────────────────────────────────────────────────────────────────────
  'eco_tips': 'Eco Tips',
  'eco_subtitle': 'Help preserve Tubigon\'s natural beauty',

  // ── Emergency ──────────────────────────────────────────────────────────────
  'emergency_contacts': 'Emergency Contacts',
  'call': 'Call',
  'hospital': 'Hospital',
  'police': 'Police',
  'fire': 'Fire Station',
  'coast_guard': 'Coast Guard',
  'tourism_office': 'Tourism Office',

  // ── Common ─────────────────────────────────────────────────────────────────
  'loading': 'Loading...',
  'loading_map': 'Loading map…',
  'retry': 'Retry',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'edit': 'Edit',
  'done': 'Done',
  'back': 'Back',
  'close': 'Close',
  'confirm': 'Confirm',
  'yes': 'Yes',
  'no': 'No',
  'ok': 'OK',
  'error': 'Error',
  'success': 'Success',
  'offline': 'Offline',
  'no_connection': 'No internet connection',
  'km_away': 'km away',
  'updated': 'Updated',
  'carbon_estimator': 'Carbon Estimator',
  'report_issue': 'Report Issue',
  'my_waste_reports': 'My Waste Reports',
  'photo_evidence': 'Photo Evidence',
  'barangay_optional': 'Barangay (optional)',
  'estimate_trip_footprint': 'Estimate Trip Footprint',
  'travel_mode': 'Travel mode',
  'distance_km': 'One-way distance (km)',
  'number_of_travelers': 'Number of travelers',
  'one_way': 'One way',
  'round_trip': 'Round trip',
  'estimated_footprint': 'Estimated footprint',
  'showing_saved_information':
      'Showing saved information. Some details may be outdated.',
  'carbon_intro':
      'Compare an estimated trip footprint using simple average transport factors.',
  'distance_help': 'Use a map or odometer estimate; maximum 5,000 km.',
  'travelers_help': 'The estimate uses passenger-kilometers.',
  'method_note': 'Method note',
  'carbon_method':
      'This estimate uses rounded average factors, not a measurement of a specific vehicle or ferry. Occupancy, fuel, traffic, and operating conditions change actual emissions. Walking and cycling show zero direct trip emissions; lifecycle impacts are excluded. The tricycle value is a planning proxy because no verified Tubigon fleet factor is available.',
  'issue_category': 'Issue Category',
  'location_landmark': 'Location / Landmark',
  'use_current_gps': 'Use Current GPS',
  'adjust_on_map': 'Adjust on Map',
  'issue_description': 'Issue Description',
  'submit_waste_report': 'Submit Waste Report',
  'remove': 'Remove',
  'status_history': 'Status history',
  'eco_guidelines': 'Eco-Tourism Guidelines',
  'advisory': 'Advisory',
  'contact': 'Contact',
  'hours': 'Hours',
  'availability': 'Availability',
  'view_map': 'View Map',
  'navigate_upper': 'Navigate',

  // Offline maps
  'offline_maps': 'Offline Maps',
  'tubigon_offline_map': 'Tubigon Offline Map',
  'download_offline_map': 'Download Offline Map',
  'download_offline_data': 'Download Offline Data',
  'open_offline_map': 'Open Offline Map',
  'update_offline_data': 'Update Offline Data',
  'delete_offline_package': 'Delete Offline Package',
  'downloaded': 'Downloaded',
  'last_synced': 'Last synced',
  'places': 'Places',
  'storage_used': 'Storage used',
  'ready': 'Ready',
  'data_only': 'Data only',
  'not_downloaded': 'Not downloaded',
  'included_offline': 'Included offline',
  'offline_places': 'Published locations and place details',
  'offline_markers_search': 'Markers, labels, categories, and local search',
  'offline_gps_distance': 'GPS and straight-line distance',
  'offline_emergency_ferry': 'Emergency and ferry snapshots',
  'offline_trip_summaries': 'Saved itinerary and reservation summaries',
  'offline_basemap_resources': 'Persistent MapLibre base-map resources',
  'web_basemap_unavailable': 'Full base-map resources are unavailable on Web',
  'download_paused': 'Download paused',
  'validating_download': 'Validating downloaded map',
  'downloading_map_resources': 'Downloading map resources',
  'updating_offline_data': 'Updating offline data',
  'download_progress_retained': 'Your downloaded progress is retained.',
  'resume': 'Resume',
  'pause': 'Pause',
  'offline_storage': 'Offline storage',
  'map_resources': 'Map resources',
  'place_information': 'Place information',
  'total_measured': 'Total measured',
  'offline_storage_note':
      'Optional image-cache usage is managed separately by the platform and is not included in this measured total.',
  'web_data_only_explanation':
      'This browser saved place data only. A persistent offline base map is unavailable on Web, so the app will not label or open it as a complete offline map.',
  'download_tubigon_offline_map': 'Download Tubigon Offline Map',
  'download_native_explanation':
      'This downloads public place data, safety and trip snapshots, plus persistent MapLibre resources for Tubigon. Size depends on map resources and cached content.',
  'download_web_explanation':
      'This saves public place data and supported snapshots. Full offline base-map resources are not supported in this Web environment.',
  'download': 'Download',
  'delete_offline_title': 'Delete downloaded Tubigon package?',
  'delete_offline_explanation':
      'This removes downloaded map resources and public offline map data. Server-saved Favorites, Itineraries, and Reservations are not deleted.',
  'offline_error_connection_required':
      'Connect to the internet to download the Tubigon offline map.',
  'offline_error_map_resources':
      'Place data is saved, but map resources could not be downloaded.',
  'offline_error_download': 'Unable to download the offline map.',
  'offline_error_interrupted':
      'Map resource download was interrupted. You can retry.',
  'offline_error_validation':
      'Downloaded resources did not pass validation. Your previous package was kept.',
  'offline_error_delete': 'Unable to delete the offline package right now.',
  'offline_error_restore':
      'The saved map package could not be verified on this device. Download it again before using offline mode.',
  'offline_package_unavailable':
      'A verified Tubigon offline map package is not available on this device. Download and validate it before opening offline mode.',
  'open_online_map': 'Open Online Map',

  // Concerns and support
  'concerns_support': 'Concerns & Support',
  'submit_concern': 'Submit Concern',
  'no_concerns': 'No concerns submitted.',
  'concern': 'Concern',
  'category': 'Category',
  'subject': 'Subject',
  'details': 'Details',
  'priority': 'Priority',
  'related_to_optional': 'Related to (optional)',
  'related_record': 'Related record',
  'no_related_records': 'No accessible related records found.',
  'attach_image_optional': 'Attach an image (optional)',
  'attachment_requirements': 'JPEG, PNG, or WebP up to 5 MB',
  'draft_attachment_reattach': 'Reattach this file before submitting.',
  'save_draft': 'Save Draft',
  'draft_saved': 'Concern draft saved on this device.',
  'draft_saved_offline':
      'You are offline, so the concern was saved as a draft.',
  'submit': 'Submit',
  'complete_concern_details': 'Complete the required concern details.',
  'related_to': 'Related to',
  'attachment': 'Attachment',
  'status': 'Status',
  'replies': 'Replies',
  'reply': 'Reply',
  'send': 'Send',
  'staff_concern_subtitle':
      'Review routed tickets without exposing internal notes.',
  'new_status': 'New',
  'assigned': 'Assigned',
  'in_progress': 'In Progress',
  'resolved': 'Resolved',
  'no_routed_concerns': 'No routed concerns.',
  'internal_staff_note': 'Internal staff note',
  'visible_to_tourist': 'Visible to the tourist',
  'workflow_status': 'Workflow status',
  'reply_workflow_note': 'Reply or workflow note',
  'internal_note': 'Internal note',
  'never_shown_tourist': 'Never shown to the tourist.',
  'escalate_to_admin': 'Escalate to Admin',
  'save_update': 'Save Update',
  'network_action_required': 'Internet connection is required for this action.',
  'check_entered_information': 'Please check the information you entered.',
  'not_authorized': 'You are not authorized to access this concern.',
  'operation_failed': 'The operation could not be completed. Please try again.',
  'guidance_reservation':
      'A reservation question is usually fastest through Reservation Messages. You may still submit this support concern.',
  'guidance_waste':
      'Use Waste Report for a location-based waste incident. Continue here for a general policy or service concern.',
  'guidance_emergency':
      'For immediate danger, call an Emergency Contact. Use this form only to request an information correction.',
  'guidance_related':
      'Choose a related record when it helps staff verify the concern without exposing unrelated account information.',
  'concern_category_general-tourism': 'General Tourism Concern',
  'concern_category_tourist-spot': 'Tourist Spot Information',
  'concern_category_reservation': 'Reservation / Booking',
  'concern_category_ferry': 'Ferry Schedule',
  'concern_category_msme': 'MSME / Business Information',
  'concern_category_waste': 'Waste / Environmental Concern',
  'concern_category_emergency-correction': 'Emergency Information Correction',
  'concern_category_account-login': 'Account / Login',
  'concern_category_role-application': 'Role Application',
  'concern_category_technical': 'System / Technical Issue',
  'concern_category_feedback': 'Suggestion / Feedback',
  'concern_category_other': 'Other',
  'label_low': 'Low',
  'label_normal': 'Normal',
  'label_high': 'High',
  'label_submitted': 'Submitted',
  'label_under_review': 'Under Review',
  'label_assigned': 'Assigned',
  'label_in_progress': 'In Progress',
  'label_needs_more_information': 'Needs More Information',
  'label_resolved': 'Resolved',
  'label_closed': 'Closed',
  'label_reopened': 'Reopened',
  'label_reservation': 'Reservation',
  'label_ferry_schedule': 'Ferry Schedule',
  'label_tourist_spot': 'Tourist Spot',
  'label_msme': 'MSME',
  'label_waste_report': 'Waste Report',
  'label_emergency_contact': 'Emergency Contact',
  'label_role_application': 'Role Application',

  // Profile language controls
  'language': 'Language',
  'select_language': 'Select Language',
  'english': 'English',
  'filipino': 'Filipino',
  'cebuano': 'Cebuano (Bisaya)',
  'map_category_plaza-park': 'Plazas & Parks',
  'map_category_church-place-of-worship': 'Churches & Places of Worship',
};
