/// English translation strings for Tubigon Smart Tourism App.
const Map<String, String> enStrings = {
  // ── App ────────────────────────────────────────────────────────────────────
  'app_name': 'Tubigon Smart Tourism',
  'app_tagline': 'Discover the Heart of Bohol',

  // ── Navigation ─────────────────────────────────────────────────────────────
  'nav_home': 'Home',
  'nav_explore': 'Explore',
  'nav_map': 'Map',
  'nav_bookings': 'Bookings',
  'nav_profile': 'Profile',

  // ── Onboarding ─────────────────────────────────────────────────────────────
  'onboarding_1_title': 'Discover Tubigon',
  'onboarding_1_desc':
      'Explore pristine beaches, lush nature trails, and historical landmarks in the heart of Bohol.',
  'onboarding_2_title': 'Plan Your Journey',
  'onboarding_2_desc':
      'Create personalized itineraries and book activities, accommodations, and ferry schedules with ease.',
  'onboarding_3_title': 'Travel Responsibly',
  'onboarding_3_desc':
      'Follow eco-friendly tips and help keep Tubigon\'s natural beauty alive for future generations.',
  'onboarding_4_title': 'Stay Connected',
  'onboarding_4_desc':
      'Access everything offline, get real-time updates, and connect with local businesses and the LGU.',
  'get_started': 'Get Started',
  'skip': 'Skip',
  'next': 'Next',

  // ── Auth ───────────────────────────────────────────────────────────────────
  'login': 'Log In',
  'register': 'Create Account',
  'logout': 'Log Out',
  'email': 'Email',
  'password': 'Password',
  'confirm_password': 'Confirm Password',
  'forgot_password': 'Forgot Password?',
  'remember_me': 'Remember me',
  'no_account': 'Don\'t have an account?',
  'have_account': 'Already have an account?',
  'sign_up': 'Sign Up',
  'sign_in': 'Sign In',
  'full_name': 'Full Name',
  'phone_number': 'Phone Number',
  'i_am_a': 'I am a',
  'tourist': 'Tourist',
  'msme_owner': 'Business Owner',
  'terms_agree': 'I agree to the Terms of Service and Privacy Policy',

  // ── Dashboard ──────────────────────────────────────────────────────────────
  'good_morning': 'Good morning',
  'good_afternoon': 'Good afternoon',
  'good_evening': 'Good evening',
  'welcome_to': 'Welcome to',
  'featured_spots': 'Featured Spots',
  'popular_destinations': 'Popular Destinations',
  'upcoming_reservations': 'Upcoming Reservations',
  'quick_actions': 'Quick Actions',
  'recently_viewed': 'Recently Viewed',
  'nearby_attractions': 'Nearby Attractions',
  'see_all': 'See All',

  // ── Tourist Spots ──────────────────────────────────────────────────────────
  'tourist_spots': 'Tourist Spots',
  'search_spots': 'Search spots...',
  'filter': 'Filter',
  'sort': 'Sort',
  'categories': 'Categories',
  'all': 'All',
  'beach': 'Beach',
  'nature': 'Nature',
  'historical': 'Historical',
  'cultural': 'Cultural',
  'adventure': 'Adventure',
  'food': 'Food',
  'eco': 'Eco',
  'accommodation': 'Accommodation',
  'entrance_fee': 'Entrance Fee',
  'free': 'Free',
  'opening_hours': 'Opening Hours',
  'reviews': 'Reviews',
  'write_review': 'Write a Review',
  'navigate': 'Navigate',
  'share': 'Share',
  'add_to_favorites': 'Add to Favorites',
  'remove_from_favorites': 'Remove from Favorites',

  // ── Reservations ───────────────────────────────────────────────────────────
  'reservations': 'Reservations',
  'book_now': 'Book Now',
  'select_date': 'Select Date',
  'select_time': 'Select Time',
  'number_of_guests': 'Number of Guests',
  'confirm_booking': 'Confirm Booking',
  'cancel_reservation': 'Cancel',
  'reschedule': 'Reschedule',
  'pending': 'Pending',
  'confirmed': 'Confirmed',
  'cancelled': 'Cancelled',
  'completed': 'Completed',

  // ── Ferry ──────────────────────────────────────────────────────────────────
  'ferry_schedules': 'Ferry Schedules',
  'tubigon_to_cebu': 'Tubigon → Cebu',
  'cebu_to_tubigon': 'Cebu → Tubigon',
  'departure': 'Departure',
  'arrival': 'Arrival',
  'fare': 'Fare',
  'operator': 'Operator',
  'on_time': 'On Time',
  'delayed': 'Delayed',

  // ── Eco ────────────────────────────────────────────────────────────────────
  'eco_tips': 'Eco Tips',
  'eco_subtitle': 'Help preserve Tubigon\'s natural beauty',

  // ── Emergency ──────────────────────────────────────────────────────────────
  'emergency_contacts': 'Emergency Contacts',
  'call': 'Call',
  'hospital': 'Hospital',
  'police': 'Police',
  'fire': 'Fire Station',
  'coast_guard': 'Coast Guard',
  'tourism_office': 'Tourism Office',

  // ── Common ─────────────────────────────────────────────────────────────────
  'loading': 'Loading...',
  'retry': 'Retry',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'edit': 'Edit',
  'done': 'Done',
  'back': 'Back',
  'close': 'Close',
  'confirm': 'Confirm',
  'yes': 'Yes',
  'no': 'No',
  'ok': 'OK',
  'error': 'Error',
  'success': 'Success',
  'offline': 'Offline',
  'no_connection': 'No internet connection',
  'km_away': 'km away',
  'updated': 'Updated',
};
