import 'en.dart';

/// Filipino translations for Tour Tubigon. The English map provides a safe
/// fallback for future keys; all current high-priority journeys are overridden.
final Map<String, String> filStrings = {
  ...enStrings,
  'app_tagline': 'Tuklasin ang Puso ng Bohol',
  'nav_home': 'Home',
  'nav_explore': 'Tuklasin',
  'nav_map': 'Mapa',
  'nav_bookings': 'Mga Booking',
  'nav_profile': 'Profile',
  'get_started': 'Magsimula',
  'skip': 'Laktawan',
  'next': 'Susunod',
  'login': 'Mag-log In',
  'register': 'Gumawa ng Account',
  'logout': 'Mag-log Out',
  'password': 'Password',
  'confirm_password': 'Kumpirmahin ang Password',
  'forgot_password': 'Nakalimutan ang Password?',
  'remember_me': 'Tandaan ako',
  'no_account': 'Wala ka pang account?',
  'have_account': 'May account ka na?',
  'sign_up': 'Mag-sign Up',
  'sign_in': 'Mag-sign In',
  'full_name': 'Buong Pangalan',
  'phone_number': 'Numero ng Telepono',
  'i_am_a': 'Ako ay',
  'tourist': 'Turista',
  'msme_owner': 'May-ari ng Negosyo',
  'good_morning': 'Magandang umaga',
  'good_afternoon': 'Magandang hapon',
  'good_evening': 'Magandang gabi',
  'welcome_to': 'Maligayang pagdating sa',
  'featured_spots': 'Mga Tampok na Lugar',
  'popular_destinations': 'Mga Sikat na Destinasyon',
  'upcoming_reservations': 'Mga Paparating na Reserbasyon',
  'quick_actions': 'Mabilisang Aksyon',
  'recently_viewed': 'Kamakailang Tiningnan',
  'nearby_attractions': 'Malalapit na Atraksyon',
  'see_all': 'Tingnan Lahat',
  'tourist_spots': 'Mga Pasyalan',
  'search_spots': 'Maghanap ng lugar...',
  'filter': 'Salain',
  'sort': 'Ayusin',
  'categories': 'Mga Kategorya',
  'all': 'Lahat',
  'beach': 'Dalampasigan',
  'nature': 'Kalikasan',
  'historical': 'Makasaysayan',
  'cultural': 'Kultura',
  'adventure': 'Pakikipagsapalaran',
  'food': 'Pagkain',
  'accommodation': 'Matutuluyan',
  'entrance_fee': 'Bayad sa Pagpasok',
  'free': 'Libre',
  'opening_hours': 'Oras ng Pagbubukas',
  'reviews': 'Mga Review',
  'write_review': 'Sumulat ng Review',
  'navigate': 'Mag-navigate',
  'share': 'Ibahagi',
  'add_to_favorites': 'Idagdag sa Mga Paborito',
  'remove_from_favorites': 'Alisin sa Mga Paborito',
  'reservations': 'Mga Reserbasyon',
  'book_now': 'Mag-book Ngayon',
  'select_date': 'Pumili ng Petsa',
  'select_time': 'Pumili ng Oras',
  'number_of_guests': 'Bilang ng Bisita',
  'confirm_booking': 'Kumpirmahin ang Booking',
  'cancel_reservation': 'Kanselahin',
  'reschedule': 'Baguhin ang Iskedyul',
  'pending': 'Nakabinbin',
  'confirmed': 'Kumpirmado',
  'cancelled': 'Kinansela',
  'completed': 'Nakumpleto',
  'ferry_schedules': 'Mga Iskedyul ng Ferry',
  'departure': 'Pag-alis',
  'arrival': 'Pagdating',
  'fare': 'Pamasahe',
  'operator': 'Operator',
  'on_time': 'Nasa Oras',
  'delayed': 'Naantala',
  'eco_tips': 'Mga Eco Tip',
  'eco_subtitle': 'Tumulong na pangalagaan ang likas na ganda ng Tubigon',
  'emergency_contacts': 'Mga Pang-emergency na Contact',
  'call': 'Tumawag',
  'hospital': 'Ospital',
  'police': 'Pulisya',
  'fire': 'Istasyon ng Bumbero',
  'coast_guard': 'Coast Guard',
  'tourism_office': 'Tanggapan ng Turismo',
  'loading': 'Naglo-load...',
  'retry': 'Subukan Muli',
  'save': 'I-save',
  'cancel': 'Kanselahin',
  'delete': 'Burahin',
  'edit': 'I-edit',
  'done': 'Tapos',
  'back': 'Bumalik',
  'close': 'Isara',
  'confirm': 'Kumpirmahin',
  'yes': 'Oo',
  'no': 'Hindi',
  'error': 'May Error',
  'success': 'Tagumpay',
  'offline': 'Offline',
  'no_connection': 'Walang koneksyon sa internet',
  'updated': 'Na-update',
  'report_issue': 'Mag-ulat ng Isyu',
  'remove': 'Alisin',
  'status_history': 'Kasaysayan ng status',
  'contact': 'Contact',
  'hours': 'Oras',
  'availability': 'Availability',
  'view_map': 'Tingnan ang Mapa',
  'offline_maps': 'Mga Offline na Mapa',
  'tubigon_offline_map': 'Offline na Mapa ng Tubigon',
  'download_offline_map': 'I-download ang Offline na Mapa',
  'download_offline_data': 'I-download ang Offline na Data',
  'open_offline_map': 'Buksan ang Offline na Mapa',
  'update_offline_data': 'I-update ang Offline na Data',
  'delete_offline_package': 'Burahin ang Offline na Package',
  'downloaded': 'Na-download',
  'last_synced': 'Huling na-sync',
  'places': 'Mga Lugar',
  'storage_used': 'Nagamit na storage',
  'ready': 'Handa',
  'data_only': 'Data lamang',
  'not_downloaded': 'Hindi pa na-download',
  'included_offline': 'Kasama sa offline',
  'offline_places': 'Mga inilathalang lugar at detalye',
  'offline_markers_search':
      'Mga marker, label, kategorya, at lokal na paghahanap',
  'offline_gps_distance': 'GPS at tuwid na distansya',
  'offline_emergency_ferry': 'Mga snapshot ng emergency at ferry',
  'offline_trip_summaries': 'Naka-save na itinerary at buod ng reservation',
  'offline_basemap_resources': 'Permanenteng MapLibre base-map resources',
  'web_basemap_unavailable':
      'Hindi available sa Web ang buong offline base map',
  'download_paused': 'Naka-pause ang download',
  'validating_download': 'Sinusuri ang na-download na mapa',
  'downloading_map_resources': 'Dina-download ang map resources',
  'updating_offline_data': 'Ina-update ang offline na data',
  'download_progress_retained': 'Napanatili ang progreso ng iyong download.',
  'resume': 'Ipagpatuloy',
  'pause': 'I-pause',
  'offline_storage': 'Offline na storage',
  'map_resources': 'Map resources',
  'place_information': 'Impormasyon ng lugar',
  'total_measured': 'Kabuuang nasukat',
  'offline_storage_note':
      'Hiwalay na pinamamahalaan ng platform ang opsyonal na image cache at hindi ito kasama sa sukat na ito.',
  'web_data_only_explanation':
      'Data ng mga lugar lamang ang na-save ng browser. Walang permanenteng offline base map sa Web, kaya hindi ito bubuksan bilang kumpletong offline na mapa.',
  'download_tubigon_offline_map': 'I-download ang Offline na Mapa ng Tubigon',
  'download_native_explanation':
      'Dina-download nito ang data ng mga lugar, safety at trip snapshots, at permanenteng MapLibre resources para sa Tubigon.',
  'download_web_explanation':
      'Sine-save nito ang data ng mga lugar at suportadong snapshot. Hindi sinusuportahan sa Web ang buong offline base map.',
  'download': 'I-download',
  'delete_offline_title': 'Burahin ang na-download na package ng Tubigon?',
  'delete_offline_explanation':
      'Aalisin nito ang map resources at pampublikong offline data. Hindi mabubura ang Favorites, Itineraries, at Reservations sa server.',
  'offline_error_connection_required':
      'Kumonekta sa internet upang i-download ang offline na mapa ng Tubigon.',
  'offline_error_map_resources':
      'Na-save ang data ng lugar, ngunit hindi na-download ang map resources.',
  'offline_error_download': 'Hindi ma-download ang offline na mapa.',
  'offline_error_interrupted':
      'Naputol ang pag-download ng mapa. Maaari mong subukan muli.',
  'offline_error_validation':
      'Hindi pumasa sa pagsusuri ang resources. Napanatili ang dati mong package.',
  'offline_error_delete': 'Hindi mabura ang offline na package ngayon.',
  'offline_error_restore':
      'Hindi masuri ang naka-save na mapa sa device na ito. I-download itong muli bago gumamit ng offline mode.',
  'offline_package_unavailable':
      'Walang beripikadong offline map package ng Tubigon sa device na ito. I-download at beripikahin muna ito bago buksan ang offline mode.',
  'open_online_map': 'Buksan ang Online na Mapa',
  'concerns_support': 'Mga Alalahanin at Suporta',
  'submit_concern': 'Magsumite ng Alalahanin',
  'no_concerns': 'Walang naisumiteng alalahanin.',
  'concern': 'Alalahanin',
  'category': 'Kategorya',
  'subject': 'Paksa',
  'details': 'Mga Detalye',
  'priority': 'Prayoridad',
  'related_to_optional': 'Kaugnay ng (opsyonal)',
  'related_record': 'Kaugnay na record',
  'no_related_records':
      'Walang nakitang kaugnay na record na maaari mong ma-access.',
  'attach_image_optional': 'Mag-attach ng larawan (opsyonal)',
  'attachment_requirements': 'JPEG, PNG, o WebP hanggang 5 MB',
  'draft_attachment_reattach': 'I-attach muli ang file na ito bago magsumite.',
  'save_draft': 'I-save ang Draft',
  'draft_saved': 'Na-save ang draft sa device na ito.',
  'draft_saved_offline':
      'Offline ka, kaya na-save bilang draft ang alalahanin.',
  'submit': 'Isumite',
  'complete_concern_details':
      'Kumpletuhin ang kinakailangang detalye ng alalahanin.',
  'related_to': 'Kaugnay ng',
  'attachment': 'Attachment',
  'status': 'Status',
  'replies': 'Mga Tugon',
  'reply': 'Tumugon',
  'send': 'Ipadala',
  'staff_concern_subtitle':
      'Suriin ang mga naka-route na ticket nang hindi inilalantad ang internal notes.',
  'new_status': 'Bago',
  'assigned': 'Naka-assign',
  'in_progress': 'Ginagawa',
  'resolved': 'Nalutas',
  'no_routed_concerns': 'Walang naka-route na alalahanin.',
  'internal_staff_note': 'Internal na tala ng staff',
  'visible_to_tourist': 'Makikita ng turista',
  'workflow_status': 'Status ng workflow',
  'reply_workflow_note': 'Tugon o tala sa workflow',
  'internal_note': 'Internal na tala',
  'never_shown_tourist': 'Hindi kailanman ipapakita sa turista.',
  'escalate_to_admin': 'I-escalate sa Admin',
  'save_update': 'I-save ang Update',
  'network_action_required': 'Kailangan ng internet para sa aksyong ito.',
  'check_entered_information': 'Pakisuri ang impormasyong inilagay mo.',
  'not_authorized': 'Hindi ka awtorisadong mag-access sa alalahaning ito.',
  'operation_failed': 'Hindi nakumpleto ang operasyon. Pakisubukan muli.',
  'guidance_reservation':
      'Karaniwang mas mabilis ang tanong sa reservation sa Reservation Messages. Maaari ka pa ring magsumite rito.',
  'guidance_waste':
      'Gamitin ang Waste Report para sa insidente ng basura na may lokasyon. Magpatuloy rito para sa pangkalahatang alalahanin.',
  'guidance_emergency':
      'Para sa agarang panganib, tumawag sa Emergency Contact. Gamitin lamang ito para sa pagwawasto ng impormasyon.',
  'guidance_related':
      'Pumili ng kaugnay na record kung makatutulong ito sa staff na masuri ang alalahanin.',
  'concern_category_general-tourism': 'Pangkalahatang Alalahanin sa Turismo',
  'concern_category_tourist-spot': 'Impormasyon sa Pasyalan',
  'concern_category_reservation': 'Reservation / Booking',
  'concern_category_ferry': 'Iskedyul ng Ferry',
  'concern_category_msme': 'Impormasyon sa MSME / Negosyo',
  'concern_category_waste': 'Alalahanin sa Basura / Kapaligiran',
  'concern_category_emergency-correction':
      'Pagwawasto ng Impormasyong Pang-emergency',
  'concern_category_account-login': 'Account / Login',
  'concern_category_role-application': 'Aplikasyon sa Tungkulin',
  'concern_category_technical': 'Isyu sa System / Teknikal',
  'concern_category_feedback': 'Mungkahi / Feedback',
  'concern_category_other': 'Iba pa',
  'label_low': 'Mababa',
  'label_normal': 'Normal',
  'label_high': 'Mataas',
  'label_submitted': 'Naisumite',
  'label_under_review': 'Sinusuri',
  'label_assigned': 'Naka-assign',
  'label_in_progress': 'Ginagawa',
  'label_needs_more_information': 'Kailangan ng Dagdag na Impormasyon',
  'label_resolved': 'Nalutas',
  'label_closed': 'Isinara',
  'label_reopened': 'Muling Binuksan',
  'language': 'Wika',
  'select_language': 'Pumili ng Wika',
  'english': 'Ingles',
  'filipino': 'Filipino',
  'cebuano': 'Cebuano (Bisaya)',
  'map_category_plaza-park': 'Mga Plaza at Parke',
  'map_category_church-place-of-worship': 'Mga Simbahan at Lugar ng Pagsamba',
};
